Title: Why I took The Jab
Author: When I am Free
Image: https://a0.awsstatic.com/main/images/logos/aws_logo_smile_1200x630.png
Theme: 282828
Questions:
    Question1:
        Type: ShortText
        Label: What is your email?
    Question2:
        Type: Text
        Label: Have you already received the 2 jabs against COVID 19 virus?
    Question3:
        Type: Radio
        Label: Do you trust this will protect you from COVID 19 virus?
        Values:
            Value1: Of course :)
            Value2: I don't think so...
            Value3: Maybe
            Value :The ill effect of the virus will be less severe
    Question4:
        Type: CheckBox
        Label: "What is the main reason you took the Jab?"
        Values:
            Value1: "This was the only option to be able to go any where in the country"
            Value2: "I feel responsible and I want to protect others"
            Value3: "There are lot of unknowns, but it makes life in the socity easier to follow the rules"
    Question5:
        Type: Text
        Label: Do you have any suggestion how can we get better prepared for the virus ?
